
COURSE_NAME = u'course_name'
TYPE = u'type'
CREDIT = u'credit'
STUDENT_CAPACITY = u'student_capacity'
TEACHER_NAME = u'teacher_name'
TEACHER_TITLE = u'teacher_title'
SCHOOL = u'school'
PERIOD = u'period'
MONDAY = u'monday'
TUESDAY = u'tuesday'
WEDNESDAY = u'wednesday'
THURSDAY = u'thursday'
FRIDAY = u'friday'
SATURDAY = u'saturday'
SUNDAY = u'sunday'
REMARKS = u'remarks'
TEXT_BOOK = u'text_book'
YEAR = u'year'
SEMESTER = u'semester'

OPERATION = u'operation'
COURSE_HEADER_STATUS = u'course_header_status'
COURSE_HEADER = u'course_header'
COURSE_NUMBER = u'course_number'
SCORE_TYPE = u'score_type'
COURSE_TYPE = u'course_type'
TEACHING_SCHOOL = u'teaching_school'
PLANNING_SCHOOL = u'planning_school'
MAJOR = u'major'

DAY = u'day'
STARTING_WEEK = u'starting_week'
ENDING_WEEK = u'ending_week'
FREQUENCY = u'frequency'
STARTING_CLASS_NUMBER = u'starting_class_number'
ENDING_CLASS_NUMBER = u'ending_class_number'
DISTRICT = u'district'
CLASSROOM = u'classroom'
BUILDING = u'building'

SCHEDULE = u'schedule'

ACTUAL_START_TIME = u'actual_start_time'
ACTUAL_END_TIME = u'actual_end_time'
WHERE = u'where'
COUNT = u'count'
BYDAY = u'byday'
